#<----------------- CREAR LA BASE DE DATOS QUE SERA LLENADA SEGUIDAMENTE DESDE NODEJS ---------->
CREATE DATABASE IF NOT EXISTS stock DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE stock;